<?php 
//error_reporting(0);
 if ( ! defined("BASEPATH")) exit("No direct script access allowed");$active_group = "default";//error_reporting(0);
$active_record = TRUE;
$db["default"]["hostname"] = "50.62.209.161";
$db["default"]["username"] = "admin2";
$db["default"]["password"] = "calzon93";
//$db["default"]["database"] ="techwbzd_callmycab";
$db["default"]["database"] = "wordpress_a5";
$db["default"]["dbdriver"] = "mysql";
$db["default"]["dbprefix"] = "";
$db["default"]["pconnect"] = TRUE;
$db["default"]["db_debug"] = FALSE;
$db["default"]["cache_on"] = FALSE;
$db["default"]["cachedir"] = "";
$db["default"]["char_set"] = "utf8";
$db["default"]["dbcollat"] = "utf8_general_ci";
$db["default"]["swap_pre"] = "";
$db["default"]["autoinit"] = TRUE;
$db["default"]["stricton"] = FALSE;
